### ISSUE TITLE
PySCF-based tests segfault on Mac OS with Python 3.8

### ISSUE THREAD

**Issue by mrossinek** [qiskit-community/qiskit-nature#1091]
### Environment

- **Qiskit Nature version**: `main` @ https://github.com/Qiskit/qiskit-nature/commit/ec47efea9856b6e4e597ac8b7c55f020ae4b10cc
- **Python version**: 3.8
- **Operating system**: MacOS

### What is happening?

Three tests starting failing in CI: https://github.com/Qiskit/qiskit-nature/commit/ec47efea9856b6e4e597ac8b7c55f020ae4b10cc

### How can we reproduce the issue?

Run the tests from `test/algorithms/excited_state_solvers/test_excited_states_solvers.py`

### What should happen?

The tests should pass.

**Comment by mrossinek** [comment]
It seems like this issue is related to PySCF because when it is not installed, the CI works fine. This will need to be investigated further in the future.

**Comment by mrossinek** [comment]
It appears as though Psi4-based tests are affected in the same way. For now, we will fully disable 3.8 on MacOS.

**Comment by rryoung98** [comment]
Just to add, I'm running python 3.9 with Mac M1 Ventura 3.1

```  × Running setup.py install for pyscf did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      scipy>1.1.0 may crash when calling scipy.linalg.eigh. (Issues https://github.com/scipy/scipy/issues/15362 https://github.com/scipy/scipy/issues/16151)
      running install
      /Users/rickyyoung/opt/anaconda3/envs/qiskit/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      cmake -S/private/var/folders/z0/w8wxtq691l55jcqndh2hzmfh0000gn/T/pip-install-h8rl5j7b/pyscf_51ed2725a8494bd0afa6490860b7313d/pyscf/lib -Bbuild/temp.macosx-11.1-arm64-cpython-39
      error: command 'cmake' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyscf
```

**Comment by woodsp-ibm** [comment]
@rryoung98 See #689 in which I also linked an issue in PySCF to build M1 wheels which is still open

PySCF 2.2.1, the latest version, shipped with a universal2 wheel that could contain both an X86 and ARM wheels. Given that the issue is still open I am guessing that it probably just includes X86 for now though I do not know for sure, but the size seems commensurate with the X86 wheels of the prior PySCF versions.

**Comment by rryoung98** [comment]
Ah thank you! @woodsp-ibm
