### ISSUE TITLE
ExcitedStatesEigensolver does not return excited states

### ISSUE THREAD

**Issue by austingmhuang** [qiskit-community/qiskit-nature#1197]
### Environment

- **Qiskit Nature version**: 0.6.2
- **Python version**:  3.10.6
- **Operating system**: Linux (WSL)

### What is happening?

Hi guys, I was running [this tutorial](https://qiskit.org/ecosystem/nature/tutorials/04_excited_states_solvers.html) on excited state solvers on my local machine and found that the ExcitedStatesEigensolver was not actually returning any excited states. When I ran the tutorial on the IBM cloud, the same error was produced. In fact that tutorial page itself does not have any excited states produced by the numpy eigensolver. 

Upon checking the Japanese (JA) version of the [same tutorial](https://qiskit.org/ecosystem/nature/locale/ja_JP/tutorials/04_excited_states_solvers.html), it seems that the tutorial used to be in fact working.

### How can we reproduce the issue?

You can check the tutorial itself, or try running the code from the tutorial and the problem should reproduce itself.

### What should happen?

The ExcitedStatesEigensolver should produce the energies for the excited states of H2.

**Comment by mrossinek** [comment]
That is very odd :eyes: 

I can indeed reproduce this locally. Two things stand out to me:

- the excited states are even missing when I remove the `filter_criterion` from the `NumPyEigensolver`
- the `QEOM` results report particle numbers of `0`

Not sure what is going on yet, but I will do some digging. Thanks for raising this! :+1:

**Comment by mrossinek** [comment]
Okay, the `NumPyEigensolver` issue was a simple mistake after the deprecation of the `NumPyEigensolverFactory`.
The number of eigenvalues computed by that solver (which exists in Terra) defaults to `k=1`. Thus, all we need to do to fix this is to set `k=4` and our issue is resolved :+1: 

(looking into the QEOM auxiliary operators next)

**Comment by mrossinek** [comment]
And with QEOM its also a matter of not having updated the tutorial. In this PR (#971) the codebase of QEOM was refactored and we introduced the `EvaluationRule` which allows the user to configure the rules for which operators to be evaluated.
I will update the tutorial accordingly.

**Comment by mrossinek** [comment]
The fixed tutorial is now live here: https://qiskit.org/ecosystem/nature/tutorials/04_excited_states_solvers.html
