### ISSUE TITLE
Why is it so slow to use vqe to compute LiH, and it's still single-core computing, isn't there a way to use multi-core or gpu?

### ISSUE THREAD

**Issue by Guogggg** [qiskit-community/qiskit-nature#1231]
### Environment

- **Qiskit Nature version**:0.6.2
- **Python version**: 3.8.6
- **Operating system**: Ubuntu 20.04

### What is happening?

I used htop to check the CPU information and found that there was only one core in the calculation, and it took about 2000 s to complete the result

### How can we reproduce the issue?

`
from qiskit_nature.units import DistanceUnit
from qiskit_nature.second_q.drivers import PySCFDriver
from qiskit_nature.second_q.mappers import JordanWignerMapper, ParityMapper
from qiskit.algorithms.minimum_eigensolvers import VQE
from qiskit.algorithms.minimum_eigensolvers import MinimumEigensolver
from qiskit.algorithms.optimizers import SLSQP
from qiskit.algorithms.optimizers import SPSA
from qiskit.algorithms.optimizers import L_BFGS_B
from qiskit.primitives import Estimator
from qiskit_nature.second_q.circuit.library import HartreeFock, UCCSD
from qiskit_nature.second_q.algorithms import GroundStateEigensolver
import time
print(sys.path)
dis = 1.5
driver = PySCFDriver(
        atom = "Li 0 0 0; H 0 0 " + str(dis),
        basis = "sto3g",
        charge = 0,
        spin = 0,
        unit = DistanceUnit.ANGSTROM,
    )
     
es_problem = driver.run()

mapper_jw = JordanWignerMapper()

ansatz = UCCSD(es_problem.num_spatial_orbitals,
		es_problem.num_particles,
                mapper_jw,
                initial_state=HartreeFock(es_problem.num_spatial_orbitals,
                                           es_problem.num_particles,
                                           mapper_jw),
                )
vqe_solver = VQE(Estimator(), ansatz, SLSQP())
vqe_solver.initial_point = [0.1] * ansatz.num_parameters

fermionic_op = es_problem.hamiltonian.second_q_op()
qubit_op = mapper_jw.map(fermionic_op)    # 12-qubit
result = vqe_solver.compute_minimum_eigenvalue(qubit_op)

calc = GroundStateEigensolver(mapper_jw, vqe_solver)
res = calc.solve(es_problem)
energy = result.eigenvalue + res.nuclear_repulsion_energy
print(energy)
`

### What should happen?

Is there a way to call a multi-core CPU or GPU?

**Comment by woodsp-ibm** [comment]
You can switch from using the reference Estimator primitive from Qiskit to using the [Estimator from Aer](https://qiskit.org/ecosystem/aer/stubs/qiskit_aer.primitives.Estimator.html). The Aer simulator has options for GPU etc. you can try that. Its Estimator can be configured in different ways and beware if you use a default instance, as you did above, as the reference primitive does an exact calculation by default, but the Aer Estimator does not. (For Aer you need to set approximation to True and shots to None as the Aer Estimator notes for an exact outcome in the above linked API ref - look at shots docstring).

The other way you can speed up things is to reduce the problem size. Freezing the core orbitals out using the FreezeCoreTransformer as well as using Parity Mapping that leverages a two qubit reduction instead of JordanWigner, from know symmetries of the mapping, will reduce the problem size. 

Just a comment - when using UCCSD you should start with all zeros as an initial point so it correctly starts from the HF state. It may achieve the correct outcome with a different point but often it will fail to converge to the expected value.

**Comment by Guogggg** [comment]
> 您可以从使用 Qiskit 的参考 Estimator 原语切换为使用[Aer 的 Estimator](https://qiskit.org/ecosystem/aer/stubs/qiskit_aer.primitives.Estimator.html)。Aer模拟器有GPU等选项，你可以尝试一下。它的 Estimator 可以通过不同的方式进行配置，如果您像上面那样使用默认实例，请注意，因为参考基元默认执行精确计算，但 Aer Estimator 不会。（对于 Aer，您需要将近似值设置为 True，将镜头设置为 None，如 Aer 估算器在上面链接的 API 参考中指出的确切结果 - 请参阅镜头文档字符串）。
> 
> 加快速度的另一种方法是缩小问题的规模。根据已知的映射对称性，使用 FreezeCoreTransformer 冻结核心轨道以及利用两个量子位减少而不是 JordanWigner 的奇偶映射，将减少问题的大小。
> 
> 只是评论 - 使用 UCCSD 时，您应该以全零作为初始点开始，以便它正确地从 HF 状态开始。它可能会在不同的点上获得正确的结果，但通常无法收敛到预期值。
Can you give me an example of using GPU to calculate LiH? thanks

**Comment by Guogggg** [comment]
> 您可以从使用 Qiskit 的参考 Estimator 原语切换为使用[Aer 的 Estimator](https://qiskit.org/ecosystem/aer/stubs/qiskit_aer.primitives.Estimator.html)。Aer模拟器有GPU等选项，你可以尝试一下。它的 Estimator 可以通过不同的方式进行配置，如果您像上面那样使用默认实例，请注意，因为参考基元默认执行精确计算，但 Aer Estimator 不会。（对于 Aer，您需要将近似值设置为 True，将镜头设置为 None，如 Aer 估算器在上面链接的 API 参考中指出的确切结果 - 请参阅镜头文档字符串）。
> 
> 加快速度的另一种方法是缩小问题的规模。根据已知的映射对称性，使用 FreezeCoreTransformer 冻结核心轨道以及利用两个量子位减少而不是 JordanWigner 的奇偶映射，将减少问题的大小。
> 
> 只是评论 - 使用 UCCSD 时，您应该以全零作为初始点开始，以便它正确地从 HF 状态开始。它可能会在不同的点上获得正确的结果，但通常无法收敛到预期值。
I use from qiskit_aer.primitives import Estimator as AerEstimator to replace from qiskit.primitives import Estimator, Then set the ```
AerEstimator(backend_options={"method": "statevector","device":"GPU"},
run_options={"shots": None},
approximation=True,)
```
However, I found that the computing time of "device" :"GPU" is about twice as slow as that of "device" :"CPU", and "device" :"CPU" uses aer's emulator, but does not use multithreading to compute

My code is as follows:

```
import numpy as np
import sys
from qiskit_nature.units import DistanceUnit
from qiskit_nature.second_q.drivers import PySCFDriver
from qiskit_nature.second_q.mappers import JordanWignerMapper, ParityMapper
from qiskit.algorithms.minimum_eigensolvers import VQE
from qiskit.algorithms.minimum_eigensolvers import MinimumEigensolver
from qiskit.algorithms.optimizers import SLSQP
from qiskit.algorithms.optimizers import SPSA
from qiskit.algorithms.optimizers import L_BFGS_B
#from qiskit.primitives import Estimator
from qiskit.primitives import BackendEstimator
from qiskit_aer import AerSimulator
from qiskit_nature.second_q.circuit.library import HartreeFock, UCCSD
from qiskit_nature.second_q.algorithms import GroundStateEigensolver
import time
from qiskit_aer.primitives import Estimator as AerEstimator
from qiskit_nature.settings import  QiskitNatureSettings
QiskitNatureSettings.use_pauli_sum_op = False
counts = []
values = []
def store_intermediate_result(eval_count, parameters, mean, std):
    counts.append(eval_count)
    values.append(mean)
dis = 1.5
driver = PySCFDriver(
        atom = "Li 0 0 0; H 0 0 " + str(dis),
        basis = "sto3g",
        charge = 0,
        spin = 0,
        unit = DistanceUnit.ANGSTROM,
    )
     
es_problem = driver.run()

mapper_jw = JordanWignerMapper()

ansatz = UCCSD(es_problem.num_spatial_orbitals,
		es_problem.num_particles,
                mapper_jw,
                initial_state=HartreeFock(es_problem.num_spatial_orbitals,
                                           es_problem.num_particles,
                                           mapper_jw),
                )
# simulation = AerSimulator()
# est_simulation = Estimator(options=simulation)

noiseless_estimator = AerEstimator(
    backend_options={"method": "statevector","device":"CPU"},
    run_options={"shots": None},
    approximation=True,
)
vqe_solver = VQE(
    noiseless_estimator, ansatz, optimizer=SLSQP()
)
#vqe_solver = VQE(noiseless_estimator(), ansatz, SLSQP())
# circuits = vqe_solver.construct_circuit(ansatz.parameters, hamiltonian)
vqe_solver.initial_point = [0.1] * ansatz.num_parameters
st = time.time()
fermionic_op = es_problem.hamiltonian.second_q_op()
qubit_op = mapper_jw.map(fermionic_op)    # 12-qubit
result = vqe_solver.compute_minimum_eigenvalue(qubit_op)

calc = GroundStateEigensolver(mapper_jw, vqe_solver)
res = calc.solve(es_problem)
energy = result.eigenvalue + res.nuclear_repulsion_energy
print(energy)
print("time used: ",time.time()-st)

```

**Comment by woodsp-ibm** [comment]
See Qiskit/qiskit-aer#1919 which also talks about Estimator and has a link to another PR with some bar graph of CPU vs GPU after the change that was done there. Bottom line is that speed in this regard is an issue in Aer. The Aer Estimator with CPU should be faster than the qiskit.primitives Estimator in general which the OP was using.

**Comment by Guogggg** [comment]
> See [Qiskit/qiskit-aer#1919](https://github.com/Qiskit/qiskit-aer/issues/1919) which also talks about Estimator and has a link to another PR with some bar graph of CPU vs GPU after the change that was done there. Bottom line is that speed in this regard is an issue in Aer. The Aer Estimator with CPU should be faster than the qiskit.primitives Estimator in general which the OP was using.

In [Qiskit/qiskit-aer/issues/1919](https://github.com/Qiskit/qiskit-aer/issues/1919)he solves multiple shots issues. I saw in the previous issue that the shots need to be set to None when setting the AerEstimator

I try to

` ` `

noiseless_estimator = AerEstimator(

backend_options={"method": "statevector","device":"CPU","max_parallel_threads":14,"statevector_parallel_threshold":6,},

run_options={"shots": None},

approximation=True,

)

` ` `

In addition to the number of parallel threads open bits, and the number of cores, htop can see that my computing core does increase, but the calculation time is longer, please ask, in

Isn't the computation in 'compute_minimum_eigenvalue' suitable for multi-core Settings? Will you change them to multi-core later, or make them GPU-accelerated?
