### ISSUE TITLE
Tutorials that are published have PySCF B3YLP warning showing

### ISSUE THREAD

**Issue by woodsp-ibm** [qiskit-community/qiskit-nature#1296]
While #1249 updated CI to suppress this for unit tests and tutorials tests, it needs doing in the `deploy_docs` workflow too, so as to suppress the same thing for when the docs that are published are built.

> /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/pyscf/dft/libxc.py:771: UserWarning: Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, corresponding to the original definition by Stephens et al. (issue 1480) and the same as the B3LYP functional in Gaussian. To restore the VWN5 definition, you can put the setting "B3LYP_WITH_VWN5 = True" in pyscf_conf.py
  warnings.warn('Since PySCF-2.3, B3LYP (and B3P86) are changed to the VWN-RPA variant, '

**Comment by julenl** [comment]
@woodsp-ibm: What about temporarily hard-coding the variable and value (B3LYP_WITH_VWN5 = True) in the driver, or something like that?

**Comment by woodsp-ibm** [comment]
We had decided not to do that so users of the driver could decide how they wanted to proceed. Having the warnings come out for us in CI was suppressed, per the referenced PR, which suppresses it in the docs it builds as well. You can see in that its a simple one liner in the workflow - well 2 if you include the comment :). However the docs that are finally deployed are a done in a separate workflow and built from scratch again and the simple fix/change. that was done for other workflows was not done for the deploy_docs. This is all that is needed/wanted.
