### ISSUE TITLE
Logarithmic mapper for `BosonicOp`

### ISSUE THREAD

**Issue by ftroisi** [qiskit-community/qiskit-nature#1345]
### What should we add?

A Logarithmic mapper for the `BosonicOp` class

### Purpose

Currently, Qiskit Nature offers many mappers for the `FermionicOp` class, but only the `BosonicLinearMapper` for the `BosonicOp` class.
As the name suggests, the number of required qubits to represent any bosonic operator scales linearly with the number of modes and Fock states used to represent each mode.
This strongly limits the possible applications of `BosonicOp` class, especially when dealing with mixed boson-fermion systems (see #795, #1188).

### How

We need to add a `BosonicLogarithmicMapper` class, which inherits from `BosonicMapper`. This class will implement the mapping in Ref [1], in particular equation 7 (which defines how to map the creation operator). We will need to map the annihilation operator as well.
The formulas can also be taken from the paper in Ref [2], equations (34, 35), and from Ref [3] equation (28, 29).

Note that this paper is published only in the Arxiv, but they are already cited and they all share the same results. Therefore, since they are independent, we can safely that their claims and formulas are correct.

### References
- [1] Huang et al., Qubitization of Bosons, https://arxiv.org/abs/2105.12563
- [2] Bo Peng et al., Quantum Simulation of Boson-Related Hamiltonians: Techniques, Effective Hamiltonian Construction, and Error Analysis, Arxiv https://doi.org/10.48550/arXiv.2307.06580
- [3] Veis et al., Quantum chemistry beyond Born-Oppenheimer approximation on a quantum computer: a simulated phase estimation study,  https://doi.org/10.48550/arXiv.1507.03271

**Comment by ftroisi** [comment]
@Anthony-Gandon I'm tagging you here after today's discussion (for some reason I couldn't find you in the `assignees`)

@mrossinek I'm tagging you as a maintainer to keep you in the loop. We discussed with Ivano that this is becoming a priority. I'm happy to work on the implementation

**Comment by woodsp-ibm** [comment]
> for some reason I couldn't find you in the assignees

In general it will take someone to make a comment in the issue before they will appear in the assignees dropdown
