### ISSUE TITLE
Add a `HexagonalLattice`

### ISSUE THREAD

**Issue by mrossinek** [qiskit-community/qiskit-nature#956]
### What should we add?

A new lattice should be added to the `qiskit_nature.second_q.hamiltonians.lattices` module, allowing the simple construction of [hexagonal lattices](https://en.wikipedia.org/wiki/Hexagonal_lattice).

Based on this class, we could then also add support for the quick construction of [heavy-hex lattices](https://research.ibm.com/blog/heavy-hex-lattice) which would be of great use for simulations on IBM Quantum devices.
I am open to discuss whether we want a `HeavyHexLattice` subclass of the `HexagonalLattice` or whether we want to a `heavy: bool = True` keyword argument for the lattice class proposed by this feature request.

(This suggestion was extracted from #43)

**Comment by javabster** [comment]
You can assign this to me 😄

**Comment by mrossinek** [comment]
Although I have marked #1027 as closing this issue, we will leave the following additions for future extension. As of now, these are not planned but may be picked up by anyone who would like to. Once they do, they should open an issue for the specific feature to be added.

- [ ] support for periodic boundary conditions
- [ ] generation of heavy-hex lattices
