### ISSUE TITLE
Add a `KagomeLattice`

### ISSUE THREAD

**Issue by mrossinek** [qiskit-community/qiskit-nature#957]
### What should we add?

A new lattice should be added to the `qiskit_nature.second_q.hamiltonians.lattices` module, allowing the simple construction of [Kagome lattices](https://en.wikipedia.org/wiki/Trihexagonal_tiling#Kagome_lattice).

(This suggestion was extracted from #43)

**Comment by Unathi-Skosana** [comment]
I'd like to work on this.
